export const IdentifyModuleTypes = {
    SIGNATURE: 'SIGNATURE',
    VIDEO_RECORD: 'VIDEO_RECORD',
    TAKE_SELFIE: 'TAKE_SELFIE',
    SPEECH_TEST: 'SPEECH_TEST',
    IDENTIFICATION_INFORMATION_WITH_CARD_PHOTO: 'IDENTIFICATION_INFORMATION_WITH_CARD_PHOTO',
    LIVENESS_TEST: 'LIVENESS_TEST',
    IDENTIFICATION_INFORMATION_WITH_NFC: 'IDENTIFICATION_INFORMATION_WITH_NFC',
    AGENT_CALL: 'AGENT_CALL'
};